custom:
  prod:
    cookieDomain: hf.codingtori.site
    frontUrl: "https://www.${custom.prod.cookieDomain}"
    backUrl: "https://api.${custom.prod.cookieDomain}"
  site:
    name: "SITE PROD"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/hf_prod
  data:
    redis:
      host: redis_1    # Docker container name으로 변경
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${custom.prod.backUrl}/login/oauth2/code/{registrationId}"
          google:
            redirect-uri: "${custom.prod.backUrl}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${custom.prod.backUrl}/login/oauth2/code/{registrationId}"
          github:
            redirect-uri: "${custom.prod.backUrl}/login/oauth2/code/{registrationId}"