custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          google:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          github:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"