spring:
  output:
    ansi:
      enabled: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          google:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
          github:
            redirect-uri: "${custom.dev.backUrl}/login/oauth2/code/{registrationId}"
  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: create # 스키마 변경 시 자동 업데이트. 스키마에 맞춰 데이터까지 바꾸진 못하는듯
