server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://172.17.0.1:3306/hf_prod
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/{registrationId}"
          google:
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/{registrationId}"
          naver:
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/{registrationId}"
          github:
            redirect-uri: "${custom.site.backUrl}/login/oauth2/code/{registrationId}"
logging:
  level:
    com.ll.demo03: INFO
    org.hibernate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: INFO
custom:
  cookie:
    domain: hf.codingtori.site